CASC_PATH = 'pre_processing_tools/haarcascade_frontalface_default.xml'
SIZE_FACE = 48
SHAPE_PREDICTOR_PATH = 'pre_processing_tools/shape_predictor_68_face_landmarks.dat'
EMOTIONS = ['Anger', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']
SAVE_DIRECTORY = 'data/'
SAVE_MODEL_FILENAME = 'emotion_detection_model'
SAVE_DATASET_IMAGES_FILENAME = 'training_data.npy'
SAVE_DATASET_LABELS_FILENAME = 'training_labels.npy'
SAVE_DATASET_IMAGES_TEST_FILENAME = 'testing_data.npy'
SAVE_DATASET_LABELS_TEST_FILENAME = 'testing_labels.npy'
